version: '3.3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./www:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./log/nginx:/var/log/nginx"
    ports:
      - 8080:80
      - 443:443
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - TZ=${TZ}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - phpfpm
      - db

  phpfpm:
    build: ./etc/php
    environment:
      - TZ=${TZ}
    volumes:
      - ./www:/var/www/html
      - ./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  adminer:
    image: adminer
    restart: always
    ports:
      - 2080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - "mysqldata:/var/lib/mysql"

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080

volumes:
  mysqldata:
